$(".miIni").click(function(){
    $("#divInicio").show();
    $("#divHistoria").hide();
    $("#divCardapio").hide();
    $("#divLocalizacao").hide();
    $("#divContatos").hide();
    $("#navMenu").hide();
    $("#divCarrossel").hide();
    $("#divPedido").hide();
    $(".miHis").removeClass("ativo");
    $(".miCar").removeClass("ativo");
    $(".miLoc").removeClass("ativo");
    $(".miCon").removeClass("ativo");
    $(".miHis").addClass("inativo");
    $(".miCar").addClass("inativo");
    $(".miLoc").addClass("inativo");
    $(".miCon").addClass("inativo");
});
$(".miHis").click(function(){
    $("#divInicio").hide();
    $("#divHistoria").show();
    $("#divCardapio").hide();
    $("#divLocalizacao").hide();
    $("#divContatos").hide();
    $("#navMenu").show();
    $("#divCarrossel").show();
    $("#divPedido").hide();
    $(".miHis").addClass("ativo");
    $(".miCar").removeClass("ativo");
    $(".miLoc").removeClass("ativo");
    $(".miCon").removeClass("ativo");
    $(".miHis").removeClass("inativo");
    $(".miCar").addClass("inativo");
    $(".miLoc").addClass("inativo");
    $(".miCon").addClass("inativo");
});
$(".miCar").click(function(){
    $("#divInicio").hide();
    $("#divHistoria").hide();
    $("#divCardapio").show();
    $("#divLocalizacao").hide();
    $("#divContatos").hide();
    $("#navMenu").show();
    $("#divCarrossel").show();
    $("#divPedido").hide();
    $(".miHis").removeClass("ativo");
    $(".miCar").addClass("ativo");
    $(".miLoc").removeClass("ativo");
    $(".miCon").removeClass("ativo");
    $(".miHis").addClass("inativo");
    $(".miCar").removeClass("inativo");
    $(".miLoc").addClass("inativo");
    $(".miCon").addClass("inativo");
});
$(".miLoc").click(function(){
    $("#divInicio").hide();
    $("#divHistoria").hide();
    $("#divCardapio").hide();
    $("#divLocalizacao").show();
    $("#divContatos").hide();
    $("#navMenu").show();
    $("#divCarrossel").show();
    $("#divPedido").hide();
    $(".miHis").removeClass("ativo");
    $(".miCar").removeClass("ativo");
    $(".miLoc").addClass("ativo");
    $(".miCon").removeClass("ativo");
    $(".miHis").addClass("inativo");
    $(".miCar").addClass("inativo");
    $(".miLoc").removeClass("inativo");
    $(".miCon").addClass("inativo");
});
$(".miCon").click(function(){
    $("#divInicio").hide();
    $("#divHistoria").hide();
    $("#divCardapio").hide();
    $("#divLocalizacao").hide();
    $("#divContatos").show();
    $("#navMenu").show();
    $("#divCarrossel").show();
    $("#divPedido").hide();
    $(".miHis").removeClass("ativo");
    $(".miCar").removeClass("ativo");
    $(".miLoc").removeClass("ativo");
    $(".miCon").addClass("ativo");
    $(".miHis").addClass("inativo");
    $(".miCar").addClass("inativo");
    $(".miLoc").addClass("inativo");
    $(".miCon").removeClass("inativo");
});
$("#btPedido").click(function(){
    $("#divContatos").hide();
    $("#divCarrossel").hide();
    $(".miCon").addClass("inativo");
    $(".miCon").removeClass("ativo");
    $("#divPedido").show();
    $("#divTamanhos").show();
});
$("#checkPequena").click(function(){
    $("#checkPequena").addClass("okIcon");
    $("#checkMedia").removeClass("okIcon");
    $("#checkFamilia").removeClass("okIcon");
    $("#checkGigante").removeClass("okIcon");
    $("#checkPequena").removeClass("removeIcon");
    $("#checkMedia").addClass("removeIcon");
    $("#checkFamilia").addClass("removeIcon");
    $("#checkGigante").addClass("removeIcon");
});
$("#checkMedia").click(function(){
    $("#checkPequena").removeClass("okIcon");
    $("#checkMedia").addClass("okIcon");
    $("#checkFamilia").removeClass("okIcon");
    $("#checkGigante").removeClass("okIcon");
    $("#checkPequena").addClass("removeIcon");
    $("#checkMedia").removeClass("removeIcon");
    $("#checkFamilia").addClass("removeIcon");
    $("#checkGigante").addClass("removeIcon");
});
$("#checkFamilia").click(function(){
    $("#checkPequena").removeClass("okIcon");
    $("#checkMedia").removeClass("okIcon");
    $("#checkFamilia").addClass("okIcon");
    $("#checkGigante").removeClass("okIcon");
    $("#checkPequena").addClass("removeIcon");
    $("#checkMedia").addClass("removeIcon");
    $("#checkFamilia").removeClass("removeIcon");
    $("#checkGigante").addClass("removeIcon");
});
$("#checkGigante").click(function(){
    $("#checkPequena").removeClass("okIcon");
    $("#checkMedia").removeClass("okIcon");
    $("#checkFamilia").removeClass("okIcon");
    $("#checkGigante").addClass("okIcon");
    $("#checkPequena").addClass("removeIcon");
    $("#checkMedia").addClass("removeIcon");
    $("#checkFamilia").addClass("removeIcon");
    $("#checkGigante").removeClass("removeIcon");
});
$("#btRemSabor1").click(function(){
    $("#pSabor1").text("Primeiro Sabor");
});
$("#btRemSabor2").click(function(){
    $("#pSabor2").text("Segundo Sabor");
});
$("#btRemSabor3").click(function(){
    $("#pSabor3").text("Terceiro Sabor");
});
$("#btRemSabor4").click(function(){
    $("#pSabor4").text("Quarto Sabor");
});
$("#btRemAdi").click(function(){
    $("#pAdicional").text("Adicional");
});